
server:
  port: 18761

eureka:
 instance:
   hostname: localhost
   prefer-ip-address: true

client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:8761/eureka/


spring:
  application:
    name: server2